name: coda_histo
channels:
  - cyclus
  - defaults
  - conda-forge
dependencies:
  - java-jdk
  - python<=3.7
  - mkl=2019.3
  - numpy==1.18.1
  - scikit-image
  - numba==0.48
  - scipy==1.4.1
  - matplotlib
  - boto3=1.10.46
  - ipympl=0.4.0
  - metaflow=2.0.2
  - nb_conda=2.2.1
  - nb_conda_kernels=2.2.2
  - pip=19.2.3
  - python-dotenv=0.10.3
  - s3fs=0.4.0
  - scikit-learn=0.22
  - seaborn=0.9.0
  - sqlalchemy=1.3.11
  - tqdm=4.40.2
  - xlrd=1.2.0
  - keras=2.3.1
  - ipykernel==5.1.4

  - pip:
    - airtable-python-wrapper==0.12.0
    - pyarrow==0.15.1
    - pytest-cov==2.8.1
    - quantiphy==2.5.0
    - opencv_python
    - pyqtgraph==0.10.0
    - natsort==7.0.1
    - tqdm==4.46.0
    - jupyterlab==2.1.2
    - mxnet-mkl
    - python-bioformats==1.5.2
    - cellpose==0.0.2.1
    - git+https://tomroseberry@bitbucket.org/codabiotherapeutics/coda_discovery.git
